// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qxdapeaowufizkwtuclv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF4ZGFwZWFvd3VmaXprd3R1Y2x2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1OTY2NjcsImV4cCI6MjA2OTE3MjY2N30.pa1ZIh5mw94VNmshZObNe0hMs06CvsVktQC10wQpunc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});